# Dockerfile
FROM python:3.10-slim


# Устанавливаем зависимости
RUN pip install --no-cache-dir --upgrade pip

# Копируем и устанавливаем requirements
COPY req.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект
COPY . .

# Запускаем бота
CMD ["python", "main.py"]